#!/bin/bash

# Add a new module to a SilverStripe checkout.
# Usage:
# 	ssaddmodule [-n]  [modulename]  [modulename:branches/0.2] [modulename:tags/0.1rc2]
# Options:
#	-n	Do not add module to the svn:externals
#


function usage() {
	echo "Usage: $0 [-n] module[:branch] [module ..]"
	exit 1
}

NOADD=0
while getopts "nh" opt; do
	case $opt in
		n)
			NOADD=1	
			shift;
			;;
		h)
			usage
			;;
	esac
done

if [ $# -lt 1 ]; then
	usage
fi

TMPFILE="/tmp/.$(basename $0).prop"

> $TMPFILE # Clear it

SUCCESS=1

if [ $NOADD -eq 0 ]; then
	svn pg svn:externals . > $TMPFILE
fi

WHERE=${WHERE=/open}

while [ $# -ge 1 ]; do
	MODULE="$1"
	BRANCH=${MODULE/*:/}
	if [ "$BRANCH" = "$MODULE" ]; then
		BRANCH='trunk'
	fi
	MODULE=${MODULE/:*/}
	shift
	URL="http://svn.silverstripe.com${WHERE}/modules/$MODULE/$BRANCH"
	echo "Seeking $MODULE at $URL"
	curl -f -I -s "$URL" > /dev/null;
	if [ $? -ne 0 ]; then
		echo "module $MODULE not found"
		SUCCESS=0
		continue
	fi
	if [ $NOADD -eq 1 ]; then
		if [ -f $MODULE ]; then
			echo "$MODULE already there"
		else
			echo "Checkout out $URL to $MODULE/"
			svn co $URL $MODULE >/dev/null
		fi
	else
		if $(grep -q $MODULE $TMPFILE); then
			echo "$MODULE already there"
		else 
			sed -i -e '/^$/d' $TMPFILE
			echo -e "$MODULE/\t $URL" >> $TMPFILE
		fi
	fi

done

if [ $SUCCESS -eq 1 ]; then
	if [ $NOADD -eq 0 ]; then
		cat $TMPFILE
		svn ps svn:externals --file $TMPFILE .
		echo
		echo
		svn up
		echo
	fi
fi
rm $TMPFILE
